
Analyzer    = 'mkShape'
Outputdir   = 'Output_Muon'
Category    = 'SMP'
Year        = '2016'
InSkim      = 'ISR_v1'
Userflags   = 'ISR_response_Muon'
#Userflags   = 'ISR_response_Muon_closureTest'
treeName    = 'recoTree/SKFlat'

samplesFile   = 'samples_muon.py'
plotFile     = 'plot.py'
variablesFile = 'variables_muon.py'
cutsFile      = 'cuts_muon.py'
nuisancesFile= 'nuisances_muon.py'
