
Analyzer    = 'mkShape'
Outputdir   = 'Output_Dressed_DRp1'
#Outputdir   = 'Output_BareLepton'
#Outputdir   = 'Output_FSRgamma'
Outputdir   = 'Output_allleptonFSRgamma'
##Outputdir   = 'Output_allleptonFSRgamma_fullphase'
Category    = 'SMP'
Year        = '2016'
InSkim      = 'ISR_v1'
Userflags   = 'ISR_gen_plots'
treeName    = 'recoTree/SKFlat'

samplesFile   = 'samples_electron.py'
plotFile     = 'plot_electron.py'
variablesFile = 'variables_electron.py'
#variablesFile = 'variables_barelepton.py'
#variablesFile = 'variables_FSRgamma.py'
variablesFile = 'variables_alllepton_FSRgamma.py'
#cutsFile      = 'cuts_electron.py'
#cutsFile      = 'cuts_barelepton.py'
#cutsFile      = 'cuts_FSRgamma.py'
cutsFile      = 'cuts_alllepton_FSRgamma.py'
#cutsFile      = 'cuts_alllepton_FSRgamma_fullphase.py'
nuisancesFile= 'nuisances_electron.py'
