
Analyzer    = 'mkShape'
Outputdir   = 'Output'
Category    = 'SMP'
Year        = '2016'
InSkim      = 'ISR_v1'
#Userflags   = 'ISR_Gen_ISR_5GeVstep'
Userflags   = 'ISR_Gen'
treeName    = 'recoTree/SKFlat'

samplesFile   = 'samples.py'
plotFile     = 'plot.py'
variablesFile = 'variables.py'
cutsFile      = 'cuts.py'
nuisancesFile= 'nuisances.py'
